### ISSUE TITLE
АХТУНГ

### ISSUE THREAD

**Issue by MrVeit** [artcoed/minecraft-site#1]
Бро, установи dotenv пекедж через `npm install dotenv`, чтобы выделять такие штуки туда + гитигнор при выборе Node шаблона не будет его записывать в репу)

https://github.com/artcoed/minecraft-site/blob/main/server/config/default.json

**Comment by artcoed** [comment]
@MrVeit Я этот проект 3.5 года назад делал, просто для истории запушил и открыл. А за заботу спасибо)
